DROP TABLE IF EXISTS artists CASCADE;
DROP TABLE IF EXISTS albums;

CREATE TABLE artists (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    genre TEXT NOT NULL
);

CREATE TABLE albums (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    year INTEGER NOT NULL,
    artist_id BIGINT NOT NULL REFERENCES artists(id) 
);